### ISSUE TITLE
portainer一直有个问题困扰我

### ISSUE THREAD

**Issue by BenBenJian** [eysp/portainer-ce#1]
容器的IP地址都是显示：10.0.3.3
而我的实际地址是192.168.3.27

这个怎么搞，通过oprtainer总是打不开对应的docker，需要输入IP才可以，好麻烦

**Comment by yspcn** [comment]
不明白你说的，如果你说的是portainer容器列表端口那里的链接打不开容器的对应web访问的话，请点击：环境-local-Public IP，在Public IP这行填入你的ip地址即可，比如你说的192.168.3.27

**Comment by KoWming** [comment]
大老，初始加载界面这个图片位置在那？我pull了Dockerhub最新的镜像。
