### ISSUE TITLE
使用模板创建应用后环境变量不显示了

### ISSUE THREAD

**Issue by rastyu** [eysp/portainer-ce#14]
## docker镜像版本
最新的6053537/portainer-ce:2.9.1 
## 使用应用模板创建后 在堆栈中重新编辑的时候 环境变量消失
![网页捕获_9-10-2023_121942_docker aito cf](https://github.com/eysp/portainer-ce/assets/48859414/20185b84-352b-478f-a231-4fe08a86a05e)

## 用官方的显示正常
![网页捕获_9-10-2023_12194_192 168 10 3](https://github.com/eysp/portainer-ce/assets/48859414/25617974-a62f-46e6-b31b-05992ab6f8ca)

**Comment by eysp** [comment]
已修复
