### ISSUE TITLE
2.19.1版部署后应用模板报错

### ISSUE THREAD

**Issue by pisice** [eysp/portainer-ce#15]
部署的事2.19.1中文社区版，在访问应用模板时报错，docker所在系统为debian-12.2.0-amd64-netinst.iso，VM虚拟机安装，可以访问google。

Get "https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json": dial tcp 0.0.0.0:443: connect: connection refused

请帮忙看一下。在线等。

**Comment by eysp** [comment]
自定义应用模板bug已修复
