### ISSUE TITLE
镜像大小不显示了，是需要时间读取吗

### ISSUE THREAD

**Issue by chaomarks** [eysp/portainer-ce#23]
感谢无私奉献

**Comment by eysp** [comment]
我自己arm64和amd64都没有问题啊

**Comment by jswxll** [comment]
我也不显示镜像大小，怀疑是不是docker版本与此不兼容，版本25.0.4

**Comment by Ador-able** [comment]
https://github.com/portainer/portainer/issues/11436    新版本docker不兼容

**Comment by chaomarks** [comment]
安装[docker-24.0.9.tgz]解决了

**Comment by eysp** [comment]
已经更新
