### ISSUE TITLE
被chrome标记为诈骗网站

### ISSUE THREAD

**Issue by charley008** [eysp/portainer-ce#9]
今天用chrome打开网站发现居然标记为危险欺诈提示
![1](https://github.com/eysp/portainer-ce/assets/24822683/5c23aa1f-c12e-4381-b3bb-92c8db56c974)
![2](https://github.com/eysp/portainer-ce/assets/24822683/c7a9d7bb-98f5-40c2-bed9-c6a6dc24facd)

**Comment by eysp** [comment]
建议启用ssl证书，检查域名的其他网站等

**Comment by charley008** [comment]
域名下的其他二级域名都正常。
